import mongoose from "mongoose";
const { Schema, model } = mongoose;
mongoose.set("toJSON", { virtuals: true, transform: (_doc, value) => { value.id = value._id?.toString(); delete value._id; delete value.__v; return value; } });
const money = { type: Number, min: 0, required: true };

const addressSchema = new Schema({ fullName: { type: String, required: true, trim: true }, phone: { type: String, required: true }, street: { type: String, required: true, trim: true }, city: { type: String, required: true, trim: true }, state: { type: String, required: true, trim: true }, pincode: { type: String, required: true, match: /^\d{6}$/ }, type: { type: String, enum: ["Home", "Work", "Other"], default: "Home" }, isDefault: { type: Boolean, default: false } }, { _id: true });

export const User = model("User", new Schema({ fullName: { type: String, trim: true, maxlength: 100 }, email: { type: String, trim: true, lowercase: true, unique: true, sparse: true }, phone: { type: String, unique: true, sparse: true }, passwordHash: String, role: { type: String, enum: ["customer", "admin", "support"], default: "customer" }, roleRef: { type: Schema.Types.ObjectId, ref: "Role", default: null }, status: { type: String, enum: ["active", "disabled"], default: "active" }, profile: { altPhone: String, gender: String, dob: String }, addresses: [addressSchema], wishlist: [{ type: Schema.Types.ObjectId, ref: "Product" }], deleteRequestedAt: Date }, { timestamps: true }));
export const Role = model("Role", new Schema({ name: { type: String, required: true, unique: true, trim: true, maxlength: 80 }, description: { type: String, maxlength: 500, default: "" }, isSuperAdmin: { type: Boolean, default: false }, permissions: [{ type: String, trim: true }] }, { timestamps: true }));

export const Otp = model("Otp", new Schema({ phone: { type: String, index: true }, codeHash: String, expiresAt: { type: Date, index: { expires: 0 } }, attempts: { type: Number, default: 0 } }, { timestamps: true }));

const variantSchema = new Schema({ color: String, size: String, sku: String, stock: { type: Number, min: 0, default: 0 }, price: Number }, { _id: false });
const comboDealSchema = new Schema({ id: String, title: String, productIds: [{ type: Schema.Types.ObjectId, ref: "Product" }], discountPercent: { type: Number, min: 0, max: 100 } }, { _id: false });
export const Product = model("Product", new Schema({ name: { type: String, required: true, trim: true, maxlength: 180 }, slug: { type: String, required: true, unique: true, lowercase: true }, sku: { type: String, required: true, unique: true, uppercase: true }, category: { type: String, required: true, index: true }, subCategory: String, brand: String, gender: { type: String, enum: ["Men", "Women", "Unisex", "Kids"] }, price: money, costPrice: { type: Number, min: 0 }, discountPercent: { type: Number, min: 0, max: 100 }, originalPrice: { type: Number, min: 0 }, stock: { type: Number, min: 0, required: true }, status: { type: String, enum: ["active", "draft", "archived"], default: "draft", index: true }, image: { type: String, required: true }, images: [String], description: { type: String, maxlength: 5000 }, features: [String], specs: { type: Map, of: String }, colors: [{ name: String, hex: String }], sizes: [String], variants: [variantSchema], tags: [String], rating: { type: Number, default: 0 }, reviewCount: { type: Number, default: 0 }, codAvailable: { type: Boolean, default: true }, returnAvailable: { type: Boolean, default: true }, exchangeAvailable: { type: Boolean, default: true }, warrantyPeriod: String, comboDealAvailable: { type: Boolean, default: true }, comboDeals: [comboDealSchema], comboProductIds: [{ type: Schema.Types.ObjectId, ref: "Product" }] }, { timestamps: true }));

export const Cart = model("Cart", new Schema({ user: { type: Schema.Types.ObjectId, ref: "User", unique: true, required: true }, items: [{ product: { type: Schema.Types.ObjectId, ref: "Product", required: true }, quantity: { type: Number, min: 1, max: 20, required: true }, color: String, size: String }] }, { timestamps: true }));
export const Coupon = model("Coupon", new Schema({ code: { type: String, required: true, unique: true, uppercase: true, trim: true }, description: String, type: { type: String, enum: ["percentage", "fixed", "bogo", "free_shipping"], required: true }, value: { type: Number, min: 0, default: 0 }, minSpend: { type: Number, min: 0, default: 0 }, category: { type: String, default: "All" }, usageLimit: { type: Number, min: 1, required: true }, used: { type: Number, min: 0, default: 0 }, expires: { type: Date, required: true }, active: { type: Boolean, default: true } }, { timestamps: true }));
export const Order = model("Order", new Schema({ orderNumber: { type: String, unique: true, index: true }, user: { type: Schema.Types.ObjectId, ref: "User", required: true }, customer: { fullName: String, email: String, phone: String }, items: [{ product: { type: Schema.Types.ObjectId, ref: "Product" }, sku: String, name: String, image: String, quantity: Number, unitPrice: Number, color: String, size: String }], shippingAddress: addressSchema, subtotal: money, discount: { type: Number, default: 0 }, shipping: { type: Number, default: 0 }, tax: { type: Number, default: 0 }, total: money, coupon: { code: String, discount: Number }, tier: { name: String, discount: Number, freeShipping: Boolean }, status: { type: String, enum: ["pending", "processing", "shipped", "delivered", "cancelled"], default: "pending" }, paymentStatus: { type: String, enum: ["paid", "unpaid", "refunded"], default: "unpaid" }, paymentMethod: { type: String, enum: ["cod", "online"], required: true }, payment: { provider: String, providerOrderId: String, providerPaymentId: String }, shipment: { carrier: String, tracking: String, status: String, eta: Date } }, { timestamps: true }));
export const Review = model("Review", new Schema({ product: { type: Schema.Types.ObjectId, ref: "Product", required: true, index: true }, user: { type: Schema.Types.ObjectId, ref: "User" }, author: { type: String, required: true }, rating: { type: Number, min: 1, max: 5, required: true }, title: { type: String, maxlength: 160 }, comment: { type: String, required: true, maxlength: 2000 }, images: [String], videoUrl: String, status: { type: String, enum: ["pending", "approved", "rejected"], default: "pending" } }, { timestamps: true }));
export const Setting = model("Setting", new Schema({ key: { type: String, unique: true }, value: Schema.Types.Mixed }, { timestamps: true }));
export const Content = model("Content", new Schema({ type: { type: String, required: true, index: true }, slug: { type: String, required: true, trim: true }, title: { type: String, required: true, trim: true, maxlength: 180 }, active: { type: Boolean, default: true }, data: { type: Schema.Types.Mixed, default: {} }, sortOrder: { type: Number, default: 0 } }, { timestamps: true }));
Content.schema.index({ type: 1, slug: 1 }, { unique: true });
export const Invoice = model("Invoice", new Schema({ invoiceNumber: { type: String, required: true, unique: true }, order: { type: Schema.Types.ObjectId, ref: "Order", required: true, unique: true }, customer: { type: Schema.Types.ObjectId, ref: "User" }, amount: money, status: { type: String, enum: ["paid", "pending", "overdue", "void"], default: "pending" }, issuedAt: { type: Date, default: Date.now }, dueAt: Date, emailedAt: Date }, { timestamps: true }));
export const PaymentGateway = model("PaymentGateway", new Schema({ name: { type: String, required: true }, provider: { type: String, required: true, unique: true }, enabled: { type: Boolean, default: false }, mode: { type: String, enum: ["test", "live"], default: "test" }, fees: String, config: { type: Schema.Types.Mixed, default: {} } }, { timestamps: true }));
