import bcrypt from "bcryptjs";
import { connectDatabase } from "./config/db.js";
import { User, Product, Coupon, Content, Setting, PaymentGateway, Role } from "./models/index.js";
await connectDatabase();

// Seed Super Admin role
const allPermissions = ["dashboard:read","dashboard:create","dashboard:update","dashboard:delete","analytics:read","analytics:create","analytics:update","analytics:delete","products:read","products:create","products:update","products:delete","orders:read","orders:create","orders:update","orders:delete","customers:read","customers:create","customers:update","customers:delete","coupons:read","coupons:create","coupons:update","coupons:delete","invoices:read","invoices:create","invoices:update","invoices:delete","shipping:read","shipping:create","shipping:update","shipping:delete","payments:read","payments:create","payments:update","payments:delete","users:read","users:create","users:update","users:delete","website_banners:read","website_banners:create","website_banners:update","website_banners:delete","website_categories:read","website_categories:create","website_categories:update","website_categories:delete","website_subcategories:read","website_subcategories:create","website_subcategories:update","website_subcategories:delete","website_nav_categories:read","website_nav_categories:create","website_nav_categories:update","website_nav_categories:delete","website_builder:read","website_builder:create","website_builder:update","website_builder:delete","settings_theme:read","settings_theme:create","settings_theme:update","settings_theme:delete"];
const superAdminRole = await Role.findOneAndUpdate({name:"Super Admin"},{name:"Super Admin",description:"Full unrestricted access across all modules.",isSuperAdmin:true,permissions:allPermissions},{upsert:true,new:true});

const adminUser = await User.findOneAndUpdate({email:"admin@metromindz.local"},{fullName:"Metromindz Admin",email:"admin@metromindz.local",passwordHash:await bcrypt.hash("ChangeMe123!",12),role:"admin",status:"active",roleRef:superAdminRole._id},{upsert:true,new:true});

// Seed Products
const products = [
  {sku:"AUR-WH-001", name:"Aurora Wireless Headphones", slug:"aurora-wireless-headphones", category:"Audio", subCategory:"Wireless Headphones", brand:"boAt", price:1499, originalPrice:1999, stock:42, status:"active", image:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800", description:"Experience studio-quality sound with active noise cancellation, custom-tuned 40mm beryllium drivers, ultra-soft memory foam earcups, and up to 35 hours of continuous wireless playback on a single charge.", features:["Active Noise Cancellation (ANC) with Transparency Mode","Custom 40mm Beryllium Drivers for crystal clear highs and deep bass","35 Hours Battery Life with Fast USB-C Quick Charge (10 min charge = 4 hrs)","Multi-Point Bluetooth 5.3 Instant Pairing with Dual Device Connect","Built-in Quad Beamforming Microphones for ultra-clear voice calls"], specs:{"Driver Unit":"40mm Beryllium Dynamic","Frequency Response":"20Hz – 40,000Hz","Bluetooth Version":"Bluetooth 5.3 (AAC, aptX HD, LDAC)","Battery Life":"35 Hours (ANC On) / 45 Hours (ANC Off)","Charging Time":"1.5 Hours via USB Type-C",Weight:"260g",Warranty:"2 Years International Replacement Warranty"}, colors:[{name:"Midnight Black",hex:"#0f172a"},{name:"Space Gray",hex:"#475569"},{name:"Arctic White",hex:"#f8fafc"}], sizes:["Standard Fit", "Pro Memory Foam Pads"], tags:["Trending", "Wireless", "ANC", "Best Seller"], rating:4.8, reviewCount:124, gender:"Unisex"},
  {sku:"NMD-BP-014", name:"Nomad Leather Backpack", slug:"nomad-leather-backpack", category:"Bags", subCategory:"Backpacks", brand:"Wildcraft", price:2190, originalPrice:3499, stock:12, status:"active", image:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800", description:"Crafted from 100% full-grain Italian leather, the Nomad Backpack combines timeless heritage aesthetics with modern functionality, featuring a padded 16-inch laptop sleeve, waterproof lining, and YKK weather-sealed zippers.", features:["100% Full-Grain Vegetable-Tanned Italian Leather","Padded Microfiber Compartment fits up to 16-inch MacBook Pro","Weatherproof YKK AquaGuard Zippers & Water-Resistant Cotton Canvas Lining","Hidden Anti-Theft Passport Pocket on back panel","Luggage Pass-Through Strap for easy airport travel"], specs:{Material:"Full-Grain Italian Leather",Capacity:"24 Liters","Laptop Compatibility":"Fits up to 16-inch Laptop",Dimensions:"44cm x 30cm x 15cm",Weight:"1.2 kg",Warranty:"Lifetime Craftsmanship Guarantee"}, colors:[{name:"Cognac Brown",hex:"#7c2d12"},{name:"Obsidian Black",hex:"#18181b"}], sizes:["24L Standard", "28L Travel Expandable"], tags:["Leather", "Backpack", "Travel", "Laptop"], rating:4.9, reviewCount:88, gender:"Unisex"},
  {sku:"EDC-MG-003", name:"Everyday Ceramic Mug", slug:"everyday-ceramic-mug", category:"Home", subCategory:"Kitchenware", brand:"Metromindz", price:185, originalPrice:299, stock:320, status:"active", image:"https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800", description:"Handcrafted stoneware coffee mug with a matte speckled glaze finish. Designed with an ergonomic wide handle and thick thermal walls to keep your morning brew hot longer.", features:["Handcrafted Durable Stoneware Ceramic","Microwave & Dishwasher Safe Glaze","12 oz (350 ml) Capacity for Coffee & Tea","Ergonomic Comfort Grip Handle"], specs:{Capacity:"350 ml (12 oz)",Material:"Stoneware Ceramic",Dishwasher:"Safe",Microwave:"Safe"}, colors:[{name:"Speckled Oat",hex:"#e2e8f0"},{name:"Terracotta",hex:"#9a3412"}], sizes:["350 ml Standard"], tags:["Ceramic", "Mug", "Kitchen", "Handcrafted"], rating:4.7, reviewCount:210, gender:"Unisex"},
  {sku:"TRL-SN-022", name:"Trailrunner Sneakers", slug:"trailrunner-sneakers", category:"Footwear", subCategory:"Running Shoes", brand:"Nike", price:1290, originalPrice:1999, stock:15, status:"active", image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800", description:"Engineered performance trail running shoes featuring responsive nitrogen-infused foam cushioning, breathable Ripstop mesh upper, and Vibram Megagrip traction lugs for rugged terrain.", features:["Vibram Megagrip Rubber Outsole with 5mm Lugs","Nitrogen-Infused High Response Midsole Cushioning","Water-Repellent Ripstop Mesh Upper","Reinforced TPU Toe Cap for Impact Protection"], specs:{"Drop Height":"6mm",Cushioning:"Max Responsiveness",Outsole:"Vibram Megagrip Rubber",Weight:"290g per shoe"}, colors:[{name:"Crimson Red",hex:"#dc2626"},{name:"Stealth Black",hex:"#090d16"}], sizes:["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"], tags:["Running", "Trail", "Sneakers", "Sports"], rating:4.8, reviewCount:64, gender:"Men"},
  {sku:"LIN-SH-041", name:"Linen Oversized Shirt", slug:"linen-oversized-shirt", category:"Apparel", subCategory:"Casual Wear", brand:"GOBOULT", price:780, originalPrice:1199, stock:55, status:"active", image:"https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800", description:"100% Organic European Flax Linen shirt designed with a relaxed oversized silhouette, mother-of-pearl buttons, and breathable airy drape ideal for warm climates.", features:["100% Organic French & Belgian Linen","Relaxed Oversized Cut with Curved Hem","Natural Shell Buttons & Chest Pocket"], specs:{Fabric:"100% Linen",Care:"Machine Wash Cold, Hang Dry"}, colors:[{name:"Natural Flax",hex:"#d6d3d1"},{name:"Sky Blue",hex:"#38bdf8"}], sizes:["S", "M", "L", "XL"], tags:["Linen", "Shirt", "Casual", "Summer"], rating:4.6, reviewCount:39, gender:"Women"},
  {sku:"SFW-W-009", name:"Smart Fitness Watch", slug:"smart-fitness-watch", category:"Electronics", subCategory:"Smartwatches", brand:"NOISE", price:1990, originalPrice:2999, stock:24, status:"active", image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800", description:"Advanced health and fitness smartwatch featuring an Always-On AMOLED Display, continuous ECG heart rate monitoring, SpO2 blood oxygen tracking, dual-frequency GPS, and 7-day battery life.", features:["1.43-inch Always-On Ultra HD AMOLED Display (1000 nits brightness)","Continuous ECG, PPG Heart Rate, SpO2 & Sleep Stage Analysis","Dual-Band Multi-Constellation GPS for exact route tracking","5 ATM Water Resistance (Swim Proof up to 50m)","7 Days Heavy Usage Battery Life (14 Days Standby)"], specs:{Display:"1.43\" AMOLED 466x466 (1000 nits)","Water Resistance":"5 ATM (50 meters)",Sensors:"ECG, SpO2, Accelerometer, Gyroscope, Barometer",Battery:"7 Days Battery Life",Connectivity:"Bluetooth 5.2, Wi-Fi, NFC",Warranty:"1 Year Official Warranty"}, colors:[{name:"Space Gray Aluminium",hex:"#334155"},{name:"Rose Gold",hex:"#f43f5e"}], sizes:["42mm Standard", "46mm Large"], tags:["Smartwatch", "Fitness", "Health", "GPS"], rating:4.9, reviewCount:156, gender:"Unisex"},
  {sku:"VDJ-JK-017", name:"Vintage Denim Jacket", slug:"vintage-denim-jacket", category:"Apparel", subCategory:"Western Wear", brand:"Metromindz", price:1450, originalPrice:2199, stock:8, status:"active", image:"https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800", description:"Classic trucker denim jacket made from heavy 14oz rigid cotton denim. Features antique brass hardware, double chest flap pockets, and adjustable waist tabs.", features:["14oz Heavyweight 100% Cotton Denim","Vintage Washed Finish & Brass Shank Buttons","Twin Chest Pockets & Side Hand Pockets"], specs:{Material:"100% Cotton Denim (14oz)",Fit:"Classic Regular Fit"}, colors:[{name:"Indigo Blue",hex:"#1e3a8a"}], sizes:["M", "L", "XL"], tags:["Denim", "Jacket", "Vintage", "Western"], rating:4.8, reviewCount:52, gender:"Men"},
  {sku:"NKE-AM-009", name:"Nike Air Max Pulse Sneakers", slug:"nike-air-max-pulse", category:"Footwear", subCategory:"Sneakers", brand:"Nike", price:3490, originalPrice:4499, stock:25, status:"active", image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800", description:"Iconic Nike cushioning with point-loaded Air units for maximum bounce, style, and everyday comfort.", features:["Nike Air Max Cushioning","Breathable Mesh Upper","Durable Rubber Outsole","Iconic Swoosh Branding"], specs:{}, colors:[{name:"White/Black",hex:"#ffffff"},{name:"Triple Black",hex:"#090d16"}], sizes:["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"], tags:["Nike", "Air Max", "Sneakers", "Lifestyle"], rating:4.9, reviewCount:112, gender:"Unisex"},
  {sku:"SNY-TV-404", name:"Sony Bravia 4K OLED TV", slug:"sony-bravia-4k-oled", category:"Electronics", subCategory:"TVs", brand:"Sony", price:84900, originalPrice:99990, stock:10, status:"active", image:"https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800", description:"Pure OLED blacks and vibrant color powered by Sony Cognitive Processor XR for cinematic home entertainment.", features:["4K OLED Display","Cognitive Processor XR","Acoustic Surface Audio+","Google TV"], specs:{}, colors:[{name:"Black",hex:"#090d16"}], sizes:["55 inch", "65 inch", "77 inch"], tags:["Sony", "TV", "OLED", "4K"], rating:4.8, reviewCount:78, gender:"Unisex"},
  {sku:"ADI-UB-011", name:"Adidas Ultraboost Light Running Shoes", slug:"adidas-ultraboost-light", category:"Footwear", subCategory:"Running Shoes", brand:"Adidas", price:2990, originalPrice:3999, stock:18, status:"active", image:"https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800", description:"Lightest Ultraboost ever made with Light BOOST cushioning and Continental Rubber outsole grip.", features:["Light BOOST Cushioning","Continental Rubber Outsole","Primeknit+ Upper","TPU Cage Support"], specs:{}, colors:[{name:"Core Black",hex:"#090d16"},{name:"Cloud White",hex:"#f8fafc"}], sizes:["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"], tags:["Adidas", "Ultraboost", "Running", "Lightweight"], rating:4.7, reviewCount:94, gender:"Unisex"},
  {sku:"SAM-TB-900", name:"Samsung Galaxy Tab S9 Ultra", slug:"samsung-galaxy-tab-s9-ultra", category:"Electronics", subCategory:"Tablets", brand:"Samsung", price:49990, originalPrice:59999, stock:14, status:"active", image:"https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800", description:"14.6-inch Dynamic AMOLED 2X display with S Pen included, IP68 water resistance, and Snapdragon 8 Gen 2 processor.", features:["14.6\" Dynamic AMOLED 2X","S Pen Included","IP68 Water Resistance","Snapdragon 8 Gen 2"], specs:{}, colors:[{name:"Graphite",hex:"#1e293b"},{name:"Beige",hex:"#d6d3d1"}], sizes:["256GB", "512GB", "1TB"], tags:["Samsung", "Tablet", "S Pen", "AMOLED"], rating:4.9, reviewCount:63, gender:"Unisex"},
];

for (const p of products) {
  await Product.updateOne({sku: p.sku}, {$setOnInsert: p}, {upsert: true});
}

await Coupon.updateOne({code:"WELCOME10"},{$setOnInsert:{code:"WELCOME10",description:"10% off your first order",type:"percentage",value:10,minSpend:499,category:"All",usageLimit:1000,used:0,expires:new Date("2027-12-31"),active:true}},{upsert:true});
await Content.updateOne({type:"categories",slug:"audio"},{$setOnInsert:{type:"categories",slug:"audio",title:"Audio",active:true,sortOrder:1,data:{description:"Headphones, earbuds and speakers",image:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600"}}},{upsert:true});

// Seed Sub-categories
const subCategories = [
  {type:"sub-categories",slug:"ethnic-wear",title:"Ethnic Wear",active:true,sortOrder:1,data:{discount:"50-80% OFF",image:"https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"casual-wear",title:"Casual Wear",active:true,sortOrder:2,data:{discount:"40-80% OFF",image:"https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"mens-activewear",title:"Men's Activewear",active:true,sortOrder:3,data:{discount:"30-70% OFF",image:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"womens-activewear",title:"Women's Activewear",active:true,sortOrder:4,data:{discount:"30-70% OFF",image:"https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"western-wear",title:"Western Wear",active:true,sortOrder:5,data:{discount:"40-80% OFF",image:"https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"sportswear",title:"Sportswear",active:true,sortOrder:6,data:{discount:"30-80% OFF",image:"https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"loungewear",title:"Loungewear",active:true,sortOrder:7,data:{discount:"30-60% OFF",image:"https://images.unsplash.com/photo-1582533561751-ef6f6ab93a2e?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"innerwear",title:"Innerwear",active:true,sortOrder:8,data:{discount:"UP TO 70% OFF",image:"https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"lingerie",title:"Lingerie",active:true,sortOrder:9,data:{discount:"UP TO 70% OFF",image:"https://images.unsplash.com/photo-1563178406-4cdc2923acbc?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"watches",title:"Watches",active:true,sortOrder:10,data:{discount:"UP TO 80% OFF",image:"https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600",category:"Electronics"}},
  {type:"sub-categories",slug:"grooming",title:"Grooming",active:true,sortOrder:11,data:{discount:"UP TO 60% OFF",image:"https://images.unsplash.com/photo-1621607512214-68297480165e?w=600",category:"Home"}},
  {type:"sub-categories",slug:"beauty-makeup",title:"Beauty & Makeup",active:true,sortOrder:12,data:{discount:"UP TO 60% OFF",image:"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600",category:"Home"}},
  {type:"sub-categories",slug:"footwear-sneakers",title:"Footwear & Sneakers",active:true,sortOrder:13,data:{discount:"UP TO 70% OFF",image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",category:"Footwear"}},
  {type:"sub-categories",slug:"handbags-totes",title:"Handbags & Totes",active:true,sortOrder:14,data:{discount:"40-75% OFF",image:"https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600",category:"Bags"}},
  {type:"sub-categories",slug:"jewelry-accessories",title:"Jewelry & Accessories",active:true,sortOrder:15,data:{discount:"UP TO 65% OFF",image:"https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600",category:"Home"}},
  {type:"sub-categories",slug:"sunglasses-eyewear",title:"Sunglasses & Eyewear",active:true,sortOrder:16,data:{discount:"30-70% OFF",image:"https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600",category:"Electronics"}},
  {type:"sub-categories",slug:"kids-wear-toys",title:"Kids Wear & Toys",active:true,sortOrder:17,data:{discount:"50-70% OFF",image:"https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600",category:"Apparel"}},
  {type:"sub-categories",slug:"home-decor-bedding",title:"Home Decor & Bedding",active:true,sortOrder:18,data:{discount:"UP TO 60% OFF",image:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600",category:"Home"}},
];

for (const sc of subCategories) {
  await Content.updateOne({type:sc.type,slug:sc.slug},{$setOnInsert:sc},{upsert:true});
}

await Content.updateOne({type:"brands",slug:"metromindz"},{$setOnInsert:{type:"brands",slug:"metromindz",title:"Metromindz",active:true,sortOrder:1,data:{}}},{upsert:true});
await Setting.updateOne({key:"shipping"},{$setOnInsert:{key:"shipping",value:{flatShippingFee:50,freeShippingMinSpend:499,codEnabled:true,estimatedDays:"3–7",blockedPincodes:[]}}},{upsert:true});
await Setting.updateOne({key:"general"},{$setOnInsert:{key:"general",value:{storeName:"Metromindz Store",currency:"INR",timezone:"Asia/Kolkata",maintenanceMode:false}}},{upsert:true});
await PaymentGateway.updateOne({provider:"razorpay"},{$setOnInsert:{name:"Razorpay",provider:"razorpay",enabled:false,mode:"test",fees:"Configure with your merchant account",config:{}}},{upsert:true});
console.log("Seed complete. Admin: admin@metromindz.local / ChangeMe123!"); process.exit(0);
